import{a as v,i as d,S as w}from"./assets/vendor-09d7c26e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const S="https://pixabay.com/api/",x="43757696-1a32682a4096c08080d446579",u=(s,t=1)=>v.get(`${S}?key=${x}`,{params:{q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});function m(s,t){if(s.total!==0){const o=s.hits.map(i=>{const{webformatURL:e,largeImageURL:r,tags:a,likes:h,views:y,comments:L,downloads:b}=i;return`<li class="card">
        <a class="gallery-link" href="${r}">
          <img src="${e}" alt="${a}">
        </a>
        <div class="card-body">
          <p class="card-text">Likes <span>${h}</span></p>
          <p class="card-text">Views <span>${y}</span></p>
          <p class="card-text">Comments <span>${L}</span></p>
          <p class="card-text">Downloads <span>${b}</span></p>
        </div>
      </li> 
      `}).join("");t.innerHTML=o}else t.innerHTML="",d.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#b52222",position:"topRight",progressBar:!1})}const f=document.querySelector(".gallery"),q=document.querySelector(".form"),p=document.querySelector(".loader"),c=document.querySelector(".load-more");let n=null,l=1,$=0;q.addEventListener("submit",C);c.addEventListener("click",g);async function C(s){s.preventDefault();const t=s.currentTarget;if(n=t.elements.query.value,n.trim()!==""){p.classList.remove("is-hidden");try{const{data:o}=await u(n);m(o,f),c.classList.remove("invisible")}catch(o){console.error(o),d.show({message:"Something went wrong!",messageColor:"#fff",backgroundColor:"#b52222",position:"topRight",progressBar:!1})}finally{t.reset(),p.classList.add("is-hidden"),P()}}}function P(){new w(".gallery a",{captionsData:"alt",captionsDelay:250,overlayOpacity:0}).refresh()}async function g(s){s.preventDefault();try{l+=1;const{data:t}=await u(n,l);f.insertAdjacentHTML("beforeend",m(t)),l>$&&(c.classList.add("invisible"),c.removeEventListener("click",g))}catch{d.error({message:"Search params is not valid",position:"topRight",timeout:2e3})}}
//# sourceMappingURL=commonHelpers.js.map
