import{i as c,S as p}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const m="https://pixabay.com/api/",g="43757696-1a32682a4096c08080d446579";function h(o){const r=new URLSearchParams({key:g,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${m}?${r}`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()})}function y(o,r){if(o.total!==0){const s=o.hits.map(a=>{const{webformatURL:e,largeImageURL:t,tags:n,likes:l,views:u,comments:d,downloads:f}=a;return`<li class="card">
        <a class="gallery-link" href="${t}">
          <img src="${e}" alt="${n}">
        </a>
        <div class="card-body">
          <p class="card-text">Likes <span>${l}</span></p>
          <p class="card-text">Views <span>${u}</span></p>
          <p class="card-text">Comments <span>${d}</span></p>
          <p class="card-text">Downloads <span>${f}</span></p>
        </div>
      </li>`}).join("");r.innerHTML=s}else r.innerHTML="",c.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#b52222",position:"topRight",progressBar:!1})}const L=document.querySelector(".gallery"),b=document.querySelector(".form"),i=document.querySelector(".loader");b.addEventListener("submit",w);function w(o){o.preventDefault();const r=o.currentTarget,s=r.elements.query.value;s.trim()!==""&&(i.classList.remove("is-hidden"),h(s).then(a=>y(a,L)).catch(a=>{c.show({message:"Something went WRONG!",error:a,messageColor:"#fff",backgroundColor:"#b52222",position:"topRight",progressBar:!1})}).finally(()=>{r.reset(),i.classList.add("is-hidden"),S()}))}function S(){new p(".gallery a",{captionsData:"alt",captionsDelay:250,overlayOpacity:0}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
